---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gha-runner
  labels:
    app: gha-runner
spec:
  selector:
    matchLabels:
      api: gha-runner
  replicas: 10
  template:
    metadata:
      labels:
        app: gha-runner
        api: gha-runner
    spec:
      containers:
        - name: gha-runner
          image: myoung34/github-runner:ubuntu-focal
          imagePullPolicy: Always
          env:
            - name: APP_ID
              valueFrom:
                secretKeyRef:
                  name: app-id
                  key: APP_ID
            - name: APP_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: app-private-key
                  key: APP_PRIVATE_KEY
            - name: REPO_URL
              value: https://github.com/jvincent-mongodb/docs-gha-self-hosted-runner-pool-k8s
            - name: RUNNER_NAME_PREFIX
              value: docs-gha-self-hosted-runner
